name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages # Cambia si usas otra rama para el despliegue

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Ajusta la versión según tus necesidades

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Cambia si tu build genera los archivos en otro directorio
